#!/bin/bash

# Change the version of the source code to the supplied value

# Check that a version information was correctly supplied
if [ "$#" -eq "0" ]
then
  echo "Checking current version numbers only..."
  TEST="true"
elif [ "$1" = "bump" ]
then
  echo "Bumping version number..."
  MAJOR=`grep 'm4_define(\[DLPUTILS_VERSION\]' ./configure.ac | sed -e 's/m4_define(\[DLPUTILS_VERSION\],\[\([0-9]\).\([0-9]\).\([0-9]\)\])/\1/g'`
  MINOR=`grep 'm4_define(\[DLPUTILS_VERSION\]' ./configure.ac | sed -e 's/m4_define(\[DLPUTILS_VERSION\],\[\([0-9]\).\([0-9]\).\([0-9]\)\])/\2/g'`
  PATCH=`grep 'm4_define(\[DLPUTILS_VERSION\]' ./configure.ac | sed -e 's/m4_define(\[DLPUTILS_VERSION\],\[\([0-9]\).\([0-9]\).\([0-9]\)\])/\3/g'`
  echo "Current version is $MAJOR.$MINOR.$PATCH"
  PATCH=$(($PATCH+1))
  echo "New version will be $MAJOR.$MINOR.$PATCH"
  TEST="false"
elif [ "$#" -ne "3" ]
then
  echo "Improper version number supplied (use 'changeversion MAJOR MINOR PATCH', 'bump' to increase patch number, or no args to check existing files)"
  exit 1
else
  MAJOR=$1
  MINOR=$2
  PATCH=$3
  TEST="false"
  echo "Changing version numbers in files (to ${MAJOR}.${MINOR}.{$PATCH}..."
fi

# Create git tag
if [ "$TEST" = "false" ]
then
  git tag -a $MAJOR.$MINOR.$PATCH -m "change version to $MAJOR.$MINOR.$PATCH"
fi

# Change files
if [ "$TEST" = "false" ]
then
  if [ "$#" -ne "3" ]
  then
    echo $USAGE1
    exit 1
  fi
  sed -i -e "s/m4_define(\[DLPUTILS_VERSION\],\[.\+\])/m4_define([DLPUTILS_VERSION],[${MAJOR}.${MINOR}.${SUB}])/g" configure.ac
  sed -i -e "s/#define MyAppVersion \"[0-9\.]*\"/#define MyAppVersion \"${MAJOR}.${MINOR}.${SUB}\"/g" -e "s/OutputBaseFilename=dlputils-[0-9\.]*/OutputBaseFilename=dlputils-${MAJOR}.${MINOR}.${SUB}/g" extra/Win32/dlputils.iss
else
  grep "m4_define(\[DLPUTILS_VERSION" configure.ac
  grep 'define MyAppVersion' extra/Win32/dlputils.iss | sed -e 's/#define MyAppVersion \"\([0-9\.]*\)\"/\1/g'
  grep "OutputBaseFilename" extra/Win32/dlputils.iss | sed 's/OutputBaseFilename=dlputils-\([0-9\.]*\)/\1/g'
fi

exit 0
