	! Reduce a CONFIG file with velocities/forces to one without
	
	! Variables
	character*100 discard,infile,outfile,header
	integer discardi
	real discardr
	real cell(9)
	character*5 atomname
	integer image,info,atomno,n,genno,genflag,m
	integer :: iargc
	real x,y,z
	! Formats
	! 'Discard' line / DL_POLY header line
14	FORMAT (A100)
15	FORMAT (A5/,3f20.14)
	! DL_Poly CONFIG 1 - data in file/image convention/???
16	FORMAT (I10,I10,A100)
	! DL_POLY CONFIG 2 - atom name/xxx/no
17	FORMAT (A5,A12,I3)
	! DL_POLY CONFIG 3 - atom positions OR forces OR velocities
18	FORMAT (A3,F17.14,A3,F17.14,A3,F17.14)
19	FORMAT (3F20.14)
20      FORMAT ("HETATM",I6,1X,A6,"RES A  444 ",3(1X,F9.4),1X,A5,I3,I2,1X,F8.5)

	! Init
	genflag=0

	! Get the file name of the CONFIG to work on....
	call getarg(1,infile)
	call getarg(2,outfile)
	
	OPEN(UNIT=11,file=infile,FORM="FORMATTED")

	! First determine which data are in the CONFIG file
	WRITE(*,*) "CONFIG file data:"
	READ(11,14) header      ! Remove the first line (simulation name)
	READ(11,16) info,image,discard
	IF (info.EQ.0) WRITE(*,*) "Type : Coordinates only."
	IF (info.EQ.1) WRITE(*,*) "Type : Coordinates and velocities."
	IF (info.EQ.2) WRITE(*,*) "Type : Coordinates, velocities and forces."
	! Check the image convention - if it is NOT zero we remove 3 lines
	IF (image.GT.0) THEN
	  READ(11,"(3F20.14)") cell
	END IF

	OPEN(UNIT=12,file=outfile,FORM="FORMATTED")
        write(12,"(A)") "REMARK BGF Generated by config2bgf."

	n = 0
	! Now do the atom position conversion
100	READ(11,17,END=200) atomname,discard,atomno
	n = n + 1
	! Read in the atomic coordinates
	READ(11,19) x,y,z
	! Skip any other lines (forces/velocities)
	DO m=1,info
	  READ(11,14) discard
	END DO
	! Now write out the next atomic data to the new bgf file
        write(12,20) n,atomname,x,y,z,atomname,0,0,0.0
        ! (A6,I6,1X,A6,"RES A  444   ",3F10.5,1X,A5,I3,I2,1X,F8.5)
	GOTO 100

200	WRITE(*,*) "Finished!"
        write(12,"(A)") "END"
        close(12)
999	CLOSE(11)
	END
