name: Continuous

on:
  push:
    branches:
    - 'develop'
    paths-ignore:
    - '.github/workflows/pr.yml'
    - '.github/workflows/release.yml'
    - 'README.md'
    - 'docs/**'

jobs:

  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: "./.github/workflows/setup"
    - name: "Build (${{ matrix.os }})"
      uses: "./.github/workflows/build"

  Package:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    needs: Build
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: "./.github/workflows/setup"
    - name: "Package (${{ matrix.os }})"
      uses: "./.github/workflows/package"

